Name:           ros-hydro-twist-mux
Version:        0.0.5
Release:        0%{?dist}
Summary:        ROS twist_mux package

Group:          Development/Libraries
License:        CC BY-NC-SA 4.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-diagnostic-updater
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-twist-mux-msgs
Requires:       ros-hydro-visualization-msgs
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-diagnostic-updater
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-rostest
BuildRequires:  ros-hydro-rostopic
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-visualization-msgs

%description
Twist multiplexer, which multiplex several velocity commands (topics) and allows
to priorize or disable them (locks).

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Sat Apr 04 2015 Enrique Fernandez <efernandez@clearpathrobotics.com> - 0.0.5-0
- Autogenerated by Bloom

* Sun Nov 16 2014 Enrique Fernandez <enrique.fernandez@pal-robotics.com> - 0.0.4-0
- Autogenerated by Bloom

* Fri Nov 14 2014 Enrique Fernandez <enrique.fernandez@pal-robotics.com> - 0.0.2-0
- Autogenerated by Bloom

* Thu Nov 13 2014 Enrique Fernandez <enrique.fernandez@pal-robotics.com> - 0.0.1-0
- Autogenerated by Bloom

